### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by zer0trip** [Viralmaniar/Passhunt#9]
SyntaxError: Missing parentheses in call to 'print'
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
        from urllib.request import urlopen
      File "/usr/lib/python3.5/urllib/request.py", line 88, in <module>
        import http.client
      File "/usr/lib/python3.5/http/client.py", line 1217, in <module>
        import ssl
      File "/tmp/pip-build-houdmkwo/ssl/ssl/__init__.py", line 140
        except SSLError, x:
                       ^
    SyntaxError: invalid syntax

    Original exception was:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-houdmkwo/ssl/setup.py", line 33
        print 'looking for', f
                          ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by bchirico** [comment]
same issue

**Comment by iNoSec** [comment]
same here

**Comment by iNoSec** [comment]
this ssl project work only with 2.6 on what i found

**Comment by lx277856602** [comment]
same issue

**Comment by Jinovas** [comment]
had same error but I found that this solution works:

> I had the same error, solved it by
editing the file and removed the special characters below the ASCII logo
in lines 22,23 and 24

And running `python3 passhunt.py`works without error so far. Pretty awesome app!

**Comment by tan2612** [comment]
this error is related to beautifulsoup
Try using ' pip install requests beautifulsoup4'
instead of 'pip3 install -r requirements.txt'
It worked in my case

**Comment by MangoYou** [comment]
这是python3安装ssl模块时会报错，该模块只支持python2.6以下安装，在ssl文件的setup.py里可以看到
